version: '3'

services:
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6380:6379"

  demo:
    build: .
    restart: on-failure
    env_file:
      - /var/jenkins_home/web.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
