spring:
  sse:
    time: 3600000

  jwt:
    key:
      access: ENC(+gokNOdq6bK9PVEn7hvZB/+VNrozm6RV5UOhZJDl6knYIMrn8d8RzA==)
      refresh: ENC(PTaCsvKGAQdd8QLvLRGwuV0abz1vAN/Qz2FL5pcWSmJj7ynd+cQXrw+56hR9qxJG)

    time:
      access: 1800000
      refresh: 604800000

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.default_batch_fetch_size: 1000
    hibernate:
      format_sql: true
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ob+dzVKsg1bScNfOj8a6QplFE6FltnndMERG1KLU0QhryvDt7Qa1tAp+ej/IZwrcJqp+ZjttWBw7WgQ+QEsE+INeI/FJsy8bMrW97+AdlA5rjWaGpGbe411UduWsXBhAEV6TMPY7DlitAx3QSsDeu/fdCa0KjAq4u4+b5F8AvuEJu+05NUpatA==)
    username: ENC(KKdwtJ1FVpyGhcAHUxakUw==)
    password: ENC(g9TrLHYx/z+QF6aahmXXAdWyY0uUWbEW7d/loDrpm18=)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EgmHF31rL10vUdDf6ctcUacv187jdbCW)
    password: ENC(Ma8GwcH4PAm0rcWIQryJIW6XXBe3HIBV)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  redis:
    host: localhost
    port: 6379

  domain:
    http://localhost:3000

  file:
    dir: "profileImg"

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  config:
    activate:
      on-profile: dev

cloud:
  aws:
    credentials:
      accessKey: ENC(cueoDaq4/zDWBIp5VYxL5mUbKtm/Ss4Kk0EtnT3K/qg=)
      secretKey: ENC(9GxzHCHL3jgJYrjiW1qjbh8klLCNC7gp6A5wzN/ubIXJ3qrKoeK3HG7WBJsWu9t0K17m5sKbQdY=)
    s3:
      bucket: koner-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
