spring:
  sse:
    time: 3600000

  jwt:
    key:
      access: ENC(+gokNOdq6bK9PVEn7hvZB/+VNrozm6RV5UOhZJDl6knYIMrn8d8RzA==)
      refresh: ENC(PTaCsvKGAQdd8QLvLRGwuV0abz1vAN/Qz2FL5pcWSmJj7ynd+cQXrw+56hR9qxJG)

    time:
      access: 1800000
      refresh: 604800000

  thymeleaf:
    prefix: classpath:/templates/ # 이메일 템플릿이 위치할 경로. classpath:를 통해 src/main/resources/ 밑으로 설정되었다.
    suffix: .html # 템플릿 파일의 확장자
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.default_batch_fetch_size: 1000
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(TzJV8dUultXperwwiD28halHGuhxf9mhrWzIQGRjwsEvkhRKioc1FxHgxnI/RT9z2UB/vMsfI3iUJBBnEVh9gCbGX1F9rINxo7L7OQFt9ObeUrMY+GVuXxg2ZgF5VPJkzlAk0IHQpAsi7rwAgtWegqumEzkPdsT0MxjrS0oZBUk7CBTPglfFOEiOfYmQT/+9nNQYwT8cy3W3IXHExRU89CwN/xhKPlYbZel2U9WoEoM=)
    username: ENC(36oN9PtBYyLcp0fOANPh3OcuFdC5HJ8h)
    password: ENC(X1CD8QjgOhHEMORMufz9dDMTJiife43z)

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Hqntsjre7+AQBxi7VRlIi54rhdkHT0gL)
    password: ENC(dIeh8wMyHQ2Jg8GUyzaia0hmkhy8Gtj9lJ7qjT0Z6n4=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  redis:
    host: redis
    port: 6379

  domain: http://koner.kr/

  file:
    dir: "profileImg/"

  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

  config:
    activate:
      on-profile: dev

cloud:
  aws:
    s3:
      accessKey: ENC(KFhqdcaVvZPTfkW/8/3YzTZ2pwTndBMdkRTocalkCXY=)
      secretKey: ENC(6WrD32/VKR5Tv1QUevYXm/ECELWdojuiqVbpnV+noVqT9Ac2tytRQs0BkR9QeZ2mkykmFW+wogU=)
      bucket: koner-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    ses:
      accessKey: ENC(3+K5eKZPmHj+YgNF0q7r+7qUWJPuTVT1emSWhK6ob1U=)
      secretKey: ENC(plmqgwgHVfFjdOffTFq4g39GNKBj1FszpMw1Pmvt31Z5OhJm54PZO/XFFpi83L8FES/2KjlrXlQ=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

janus:
  server: ENC(H6up5neCg2kjSg54kUq7rRxocDWq65513Tnq9RKP4fRyllBaNnFocg==)
  admin:
    secret: ENC(0xz2rIeZb6jQwQ0XJKFjFCEuyydFK1eM)